using System;
using System.Collections.Generic;

namespace Nfe.Client.Tests.Models
{
    public partial class FA_TIPI_NCM
    {
        public string NCM_CODIGO { get; set; }
        public string NCM_DESCRICAO { get; set; }
        public decimal NCM_IPI { get; set; }
        public Nullable<int> NCM_ST_AC { get; set; }
        public Nullable<int> NCM_ST_AL { get; set; }
        public Nullable<int> NCM_ST_AP { get; set; }
        public Nullable<int> NCM_ST_AM { get; set; }
        public Nullable<int> NCM_ST_BA { get; set; }
        public Nullable<int> NCM_ST_CE { get; set; }
        public Nullable<int> NCM_ST_DF { get; set; }
        public Nullable<int> NCM_ST_ES { get; set; }
        public Nullable<int> NCM_ST_GO { get; set; }
        public Nullable<int> NCM_ST_MA { get; set; }
        public Nullable<int> NCM_ST_MT { get; set; }
        public Nullable<int> NCM_ST_MS { get; set; }
        public Nullable<int> NCM_ST_MG { get; set; }
        public Nullable<int> NCM_ST_PA { get; set; }
        public Nullable<int> NCM_ST_PB { get; set; }
        public Nullable<int> NCM_ST_PR { get; set; }
        public Nullable<int> NCM_ST_PE { get; set; }
        public Nullable<int> NCM_ST_PI { get; set; }
        public Nullable<int> NCM_ST_RJ { get; set; }
        public Nullable<int> NCM_ST_RN { get; set; }
        public Nullable<int> NCM_ST_RS { get; set; }
        public Nullable<int> NCM_ST_RO { get; set; }
        public Nullable<int> NCM_ST_RR { get; set; }
        public Nullable<int> NCM_ST_SC { get; set; }
        public Nullable<int> NCM_ST_SP { get; set; }
        public Nullable<int> NCM_ST_SE { get; set; }
        public Nullable<int> NCM_ST_TO { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_AC { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_AL { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_AP { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_AM { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_BA { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_CE { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_DF { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_ES { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_GO { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_MA { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_MT { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_MS { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_MG { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_PA { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_PB { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_PR { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_PE { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_PI { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_RJ { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_RN { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_RS { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_RO { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_RR { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_SC { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_SP { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_SE { get; set; }
        public Nullable<decimal> NCM_ALIQUOTA_ICMS_TO { get; set; }
        public Nullable<decimal> NCM_IVA_AC { get; set; }
        public Nullable<decimal> NCM_IVA_AL { get; set; }
        public Nullable<decimal> NCM_IVA_AP { get; set; }
        public Nullable<decimal> NCM_IVA_AM { get; set; }
        public Nullable<decimal> NCM_IVA_BA { get; set; }
        public Nullable<decimal> NCM_IVA_CE { get; set; }
        public Nullable<decimal> NCM_IVA_DF { get; set; }
        public Nullable<decimal> NCM_IVA_ES { get; set; }
        public Nullable<decimal> NCM_IVA_GO { get; set; }
        public Nullable<decimal> NCM_IVA_MA { get; set; }
        public Nullable<decimal> NCM_IVA_MT { get; set; }
        public Nullable<decimal> NCM_IVA_MS { get; set; }
        public Nullable<decimal> NCM_IVA_MG { get; set; }
        public Nullable<decimal> NCM_IVA_PA { get; set; }
        public Nullable<decimal> NCM_IVA_PB { get; set; }
        public Nullable<decimal> NCM_IVA_PR { get; set; }
        public Nullable<decimal> NCM_IVA_PE { get; set; }
        public Nullable<decimal> NCM_IVA_PI { get; set; }
        public Nullable<decimal> NCM_IVA_RJ { get; set; }
        public Nullable<decimal> NCM_IVA_RN { get; set; }
        public Nullable<decimal> NCM_IVA_RS { get; set; }
        public Nullable<decimal> NCM_IVA_RO { get; set; }
        public Nullable<decimal> NCM_IVA_RR { get; set; }
        public Nullable<decimal> NCM_IVA_SC { get; set; }
        public Nullable<decimal> NCM_IVA_SP { get; set; }
        public Nullable<decimal> NCM_IVA_SE { get; set; }
        public Nullable<decimal> NCM_IVA_TO { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_AC { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_AL { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_AP { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_AM { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_BA { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_CE { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_DF { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_ES { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_GO { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_MA { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_MT { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_MS { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_MG { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_PA { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_PB { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_PR { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_PE { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_PI { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_RJ { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_RN { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_RS { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_RO { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_RR { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_SC { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_SP { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_SE { get; set; }
        public Nullable<decimal> NCM_IVA_IMP_TO { get; set; }
        public Nullable<decimal> NCM_IPI_IMP { get; set; }
        public Nullable<decimal> NCM_COFINS_IMP { get; set; }
        public Nullable<decimal> NCM_II { get; set; }
        public Nullable<decimal> NCM_PIS_IMP { get; set; }
    }
}
